[package]
name = "gzmo-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "gzmo"
path = "src/main.rs"

[dependencies]
gzmo-core = { path = "../gzmo-core" }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true }
gzmo-chaos = { path = "../gzmo-chaos" }
ratatui = "0.26.0"
crossterm = { version = "0.27.0", features = ["event-stream"] }
color-eyre = "0.6"
futures = "0.3"
tui-input = "0.8"
sysinfo = "0.38"
fs2 = "0.4.3"
uuid = { workspace = true }
