#!/usr/bin/env bash
# OpenClaw operator morning brief — reads data-next artifacts and outputs a markdown summary
set -euo pipefail
shopt -s nullglob

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA="${GZMO_DATA_NEXT:-$ROOT/data-next}"

newest_file() {
    local latest=""
    local candidate

    for candidate in "$@"; do
        if [[ -z "$latest" || "$candidate" -nt "$latest" ]]; then
            latest="$candidate"
        fi
    done

    printf '%s' "$latest"
}

echo "🌅 GZMO Morning Brief — $(date '+%Y-%m-%d %H:%M %Z')"
echo ""

# Ops-health
if [[ -f "$DATA/ops-health/latest.md" ]]; then
    echo "## 🏥 Ops Health"
    cat "$DATA/ops-health/latest.md"
    echo ""
fi

# Serendipity digest
if [[ -f "$DATA/serendipity/digest-$(date +%Y-%m-%d).md" ]]; then
    echo "## ✨ Serendipity"
    cat "$DATA/serendipity/digest-$(date +%Y-%m-%d).md"
    echo ""
elif [[ -f "$DATA/serendipity/latest.md" ]]; then
    echo "## ✨ Serendipity (latest)"
    cat "$DATA/serendipity/latest.md"
    echo ""
fi

# Research scan
if [[ -f "$DATA/research-scan/latest.md" ]]; then
    echo "## 🔬 Research Scan"
    cat "$DATA/research-scan/latest.md"
    echo ""
fi

# Research gaps
gap_files=("$DATA/research-scan"/gaps-*.json)
if (( ${#gap_files[@]} > 0 )); then
    latest_gaps="$(newest_file "${gap_files[@]}")"
    echo "### Research Gaps"
    if ! python3 - "$latest_gaps" <<'PY'
import json
import sys

try:
    with open(sys.argv[1]) as f:
        payload = json.load(f)
except (OSError, json.JSONDecodeError) as exc:
    print(f"(gap parse failed: {exc})")
    raise SystemExit(0)

if isinstance(payload, dict):
    gaps = payload.get("gaps")
elif isinstance(payload, list):
    gaps = payload
else:
    gaps = None

if not isinstance(gaps, list):
    print("(gap parse failed: not a list or dict)")
    raise SystemExit(0)

valid_gaps = [gap for gap in gaps if isinstance(gap, dict)]
skipped = len(gaps) - len(valid_gaps)
if skipped:
    print(f"(skipped {skipped} malformed gap item(s))")

if not valid_gaps:
    print("(no valid gaps in latest scan)")

for gap in valid_gaps:
    title = next(
        (
            value
            for key in ("title", "query", "topic")
            if (value := gap.get(key)) is not None and str(value).strip()
        ),
        "?",
    )
    print(f"- {str(title).strip()[:120]}")
PY
    then
        echo "(gap parse failed: python error)"
    fi
    echo ""
fi

# Research inbox
inbox=("$DATA/inbox/research/"*.md)
if ls "$DATA/inbox/research/"*.md &>/dev/null 2>&1; then
    echo "### 📥 Research Inbox"
    for f in "$DATA/inbox/research/"*.md; do
        title=$(head -1 "$f" 2>/dev/null | sed 's/^# //')
        echo "- $title"
    done
fi
echo ""

# Tinyfolder (latest drop)
drop_files=("$DATA/tinyfolder-inbox"/drop-*.md)
if (( ${#drop_files[@]} > 0 )); then
    latest_drop="$(newest_file "${drop_files[@]}")"
    echo "## 📦 TinyFolder (latest drop)"
    cat "$latest_drop"
    echo ""
fi

# Distill queue
queue=("$DATA/distill-queue"/*.jsonl)
if (( ${#queue[@]} > 0 )); then
    echo "## 🧪 Distill Queue"
    for f in "${queue[@]}"; do
        lines=$(wc -l < "$f")
        echo "- $(basename "$f"): $lines entries"
    done
fi
echo ""

# Evolve daily log
if [[ -f "$DATA/ecosystem-evolve/daily.log" ]]; then
    echo "## 🔄 Evolve Daily"
    tail -5 "$DATA/ecosystem-evolve/daily.log" 2>/dev/null | sed 's/^/  /'
fi

echo ""

# Stigmergy Board
STIGMERGY_ROOT="${HOME}/.memory/stigmergy"
if [[ -d "$STIGMERGY_ROOT" ]]; then
    echo "## 📋 Stigmergy Board"
    for lane in pending claimed done; do
        lane_files=("$STIGMERGY_ROOT/$lane"/*.json)
        count=${#lane_files[@]}
        echo "- $lane: $count tasks"
        if [[ "$lane" == "pending" && "$count" -gt 0 ]]; then
            for f in "${lane_files[@]}"; do
                tid=$(basename "$f" .json)
                echo "  ○ $tid"
            done
        fi
        if [[ "$lane" == "done" && "$count" -gt 0 ]]; then
            sorted_done=("${lane_files[@]}")
            for ((i = 0; i < ${#sorted_done[@]}; i++)); do
                for ((j = i + 1; j < ${#sorted_done[@]}; j++)); do
                    if [[ "${sorted_done[$j]}" -nt "${sorted_done[$i]}" ]]; then
                        tmp="${sorted_done[$i]}"
                        sorted_done[$i]="${sorted_done[$j]}"
                        sorted_done[$j]="$tmp"
                    fi
                done
            done

            recent_done=""
            recent_count=${#sorted_done[@]}
            if (( recent_count > 3 )); then
                recent_count=3
            fi
            for ((i = 0; i < recent_count; i++)); do
                recent_done+="$(basename "${sorted_done[$i]}" .json), "
            done
            echo "  (last 3: ${recent_done%, })"
        fi
    done
    echo ""
fi

echo "---"
echo "Brief generated by OpenClaw operator surface"
