#!/usr/bin/env bash
# OpenClaw operator morning brief — reads data-next artifacts and outputs a markdown summary
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA="${GZMO_DATA_NEXT:-$ROOT/data-next}"

echo "🌅 GZMO Morning Brief — $(date '+%Y-%m-%d %H:%M %Z')"
echo ""

# Ops-health
if [[ -f "$DATA/ops-health/latest.md" ]]; then
    echo "## 🏥 Ops Health"
    cat "$DATA/ops-health/latest.md"
    echo ""
fi

# Serendipity digest
if [[ -f "$DATA/serendipity/digest-$(date +%Y-%m-%d).md" ]]; then
    echo "## ✨ Serendipity"
    cat "$DATA/serendipity/digest-$(date +%Y-%m-%d).md"
    echo ""
elif [[ -f "$DATA/serendipity/latest.md" ]]; then
    echo "## ✨ Serendipity (latest)"
    cat "$DATA/serendipity/latest.md"
    echo ""
fi

# Research scan
if [[ -f "$DATA/research-scan/latest.md" ]]; then
    echo "## 🔬 Research Scan"
    cat "$DATA/research-scan/latest.md"
    echo ""
fi

# Research gaps
gaps=("$DATA/research-scan/gaps-"*.json)
if [[ -f "${gaps[0]}" ]]; then
    latest_gaps=$(ls -t "$DATA/research-scan"/gaps-*.json 2>/dev/null | head -1)
    if [[ -n "$latest_gaps" ]]; then
        echo "### Research Gaps"
        python3 -c "
import json
with open('$latest_gaps') as f:
    gaps = json.load(f)
for g in gaps:
    print(f'- {g.get(\"title\", g.get(\"query\", \"?\"))[:120]}')
" 2>/dev/null || echo "(gap parse failed)"
    fi
    echo ""
fi

# Research inbox
inbox=("$DATA/inbox/research/"*.md)
if ls "$DATA/inbox/research/"*.md &>/dev/null 2>&1; then
    echo "### 📥 Research Inbox"
    for f in "$DATA/inbox/research/"*.md; do
        title=$(head -1 "$f" 2>/dev/null | sed 's/^# //')
        echo "- $title"
    done
fi
echo ""

# Tinyfolder (latest drop)
latest_drop=$(ls -t "$DATA/tinyfolder-inbox"/drop-*.md 2>/dev/null | head -1)
if [[ -n "$latest_drop" ]]; then
    echo "## 📦 TinyFolder (latest drop)"
    cat "$latest_drop"
    echo ""
fi

# Distill queue
queue=("$DATA/distill-queue"/*.jsonl)
if ls "$DATA/distill-queue"/*.jsonl &>/dev/null 2>&1; then
    echo "## 🧪 Distill Queue"
    for f in "$DATA/distill-queue"/*.jsonl; do
        lines=$(wc -l < "$f")
        echo "- $(basename "$f"): $lines entries"
    done
fi
echo ""

# Evolve daily log
if [[ -f "$DATA/ecosystem-evolve/daily.log" ]]; then
    echo "## 🔄 Evolve Daily"
    tail -5 "$DATA/ecosystem-evolve/daily.log" 2>/dev/null | sed 's/^/  /'
fi

echo ""
echo "---"
echo "Brief generated by OpenClaw operator surface"

# Stigmergy Board
STIGMERGY_ROOT="${HOME}/.memory/stigmergy"
if [[ -d "$STIGMERGY_ROOT" ]]; then
    echo "## 📋 Stigmergy Board"
    for lane in pending claimed done; do
        count=$(ls "$STIGMERGY_ROOT/$lane"/*.json 2>/dev/null | wc -l)
        echo "- $lane: $count tasks"
        if [[ "$lane" == "pending" && "$count" -gt 0 ]]; then
            for f in "$STIGMERGY_ROOT/$lane"/*.json; do
                tid=$(basename "$f" .json)
                echo "  ○ $tid"
            done
        fi
        if [[ "$lane" == "done" && "$count" -gt 0 ]]; then
            echo "  (last 3: $(ls -t "$STIGMERGY_ROOT/$lane"/*.json 2>/dev/null | head -3 | while read f; do basename "$f" .json; done | tr '\n' ', '))"
        fi
    done
    echo ""
fi

# Research gaps count
GAP_COUNT=$(ls "$DATA/research-scan"/gaps-*.json 2>/dev/null | wc -l)
echo "## 🔬 Research Gaps: $GAP_COUNT scan snapshots"
LATEST_GAP=$(ls -t "$DATA/research-scan"/gaps-*.json 2>/dev/null | head -1)
if [[ -n "$LATEST_GAP" ]]; then
    python3 -c "
import json
with open('$LATEST_GAP') as f:
    gaps = json.load(f)
print(f'- {len(gaps)} gaps in latest scan')
for g in gaps[:5]:
    print(f'  • {g.get(\"title\", g.get(\"query\", \"?\"))[:80]}')
" 2>/dev/null
fi
echo ""
