[package]
name = "gzmo-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }
rusqlite = { workspace = true }
pulldown-cmark = { workspace = true }
notify = { workspace = true }
reqwest = { workspace = true }
reqwest-eventsource = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
futures-util = { workspace = true }
sysinfo = "0.38"
tokio-cron-scheduler = "0.13"
rmcp = { version = "0.16", features = ["client", "server", "macros", "transport-child-process", "transport-io"] }
schemars = "0.8"
gzmo-chaos = { path = "../gzmo-chaos" }
r2d2 = "0.8.10"
r2d2_sqlite = "0.25.0"
fs2 = "0.4"
redis = { workspace = true }
sha2 = { workspace = true }

[lints]
workspace = true
